=== nirjo/SAMS/packages/saasify-cli/lib/schemas/config.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/Config",
  "definitions": {
    "Config": {
      "title": "Config",
      "type": "object",
      "properties": {
        "saasifyVersion": {
          "title": "saasifyVersion",
          "default": 1,
          "oneOf": [{ "type": "number" }, { "type": "string" }]
        },
        "version": {
          "title": "version",
          "default": "0.1.0",
          "oneOf": [{ "type": "number" }, { "type": "string" }]
        },
        "name": {
          "type": "string",
          "title": "name"
        },
        "description": {
          "type": "string",
          "title": "description"
        },
        "alias": {
          "type": "string",
          "title": "alias"
        },
        "build": {
          "type": "object",
          "title": "build",
          "additionalProperties": true
        },
        "env": {
          "type": "object",
          "title": "env",
          "additionalProperties": true
        },
        "saas": {
          "type": "object",
          "title": "saas",
          "additionalProperties": true
        },
        "openapi": {
          "title": "openapi",
          "oneOf": [
            { "type": "object", "additionalProperties": true },
            { "type": "string" }
          ]
        },
        "services": {
          "type": "array",
          "title": "services",
          "items": {
            "$ref": "#/definitions/Service"
          }
        },
        "coupons": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Coupon"
          },
          "title": "coupons"
        },
        "headers": {
          "type": "object",
          "title": "headers",
          "additionalProperties": true
        },
        "immutable": {
          "type": "boolean",
          "title": "immutable"
        },
        "pricingPlans": {
          "type": "array",
          "minItems": 2,
          "maxItems": 5,
          "items": {
            "$ref": "#/definitions/PricingPlan"
          },
          "title": "pricingPlans"
        }
      },
      "additionalProperties": false
    },
    "Example": {
      "title": "Example",
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "title": "name"
        },
        "description": {
          "type": "string",
          "title": "description"
        },
        "input": {
          "type": "object",
          "title": "input"
        },
        "inputContentType": {
          "type": "string",
          "title": "inputContentType"
        },
        "snippet": {
          "$ref": "#/definitions/Snippet",
          "title": "snippet"
        },
        "additionalProperties": false
      },
      "required": ["name", "input"]
    },
    "Coupon": {
      "title": "Coupon",
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "title": "name"
        },
        "currency": {
          "type": "string",
          "title": "currency"
        },
        "amount_off": {
          "type": "number",
          "title": "amount_off"
        },
        "percent_off": {
          "type": "number",
          "title": "percent_off"
        },
        "duration": {
          "type": "string",
          "title": "duration"
        },
        "duration_in_months": {
          "type": "number",
          "title": "duration_in_months"
        },
        "redeem_by": {
          "type": "string",
          "title": "redeem_by"
        },
        "max_redemptions": {
          "type": "number",
          "title": "max_redemptions"
        },
        "additionalProperties": false
      },
      "required": ["duration"]
    },
    "Service": {
      "title": "Service",
      "type": "object",
      "properties": {
        "src": {
          "type": "string",
          "title": "src"
        },
        "name": {
          "type": "string",
          "title": "name"
        },
        "path": {
          "type": "string",
          "title": "path"
        },
        "timeout": {
          "type": "number",
          "title": "timeout"
        },
        "examples": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Example"
          },
          "title": "examples"
        },
        "config": {
          "type": "object",
          "title": "config",
          "additionalProperties": true
        },
        "GET": {
          "type": "boolean",
          "title": "GET"
        },
        "POST": {
          "type": "boolean",
          "title": "POST"
        },
        "headers": {
          "type": "object",
          "title": "headers",
          "additionalProperties": true
        },
        "immutable": {
          "type": "boolean",
          "title": "immutable"
        },
        "reportUsage": {
          "type": "boolean",
          "title": "reportUsage"
        },
        "rateLimit": {
          "oneOf": [{ "$ref": "#/definitions/RateLimit" }, { "type": "null" }],
          "title": "rateLimit"
        },
        "pricingPlanConfig": {
          "type": "object",
          "title": "pricingPlanConfig",
          "patternProperties": {
            "^.*$": { "$ref": "#/definitions/PricingPlanServiceConfig" }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    },
    "RateLimit": {
      "title": "RateLimit",
      "type": "object",
      "properties": {
        "requests": {
          "type": "boolean",
          "title": "enabled",
          "default": true
        },
        "requestsInterval": {
          "title": "requestsInterval",
          "default": "1h",
          "oneOf": [{ "type": "number" }, { "type": "string" }]
        },
        "requestsMaxPerInterval": {
          "type": "number",
          "title": "requestsMaxPerInterval",
          "default": 1000
        }
      },
      "additionalProperties": false
    },
    "Snippet": {
      "title": "Snippet",
      "type": "object",
      "properties": {
        "label": {
          "type": "string",
          "title": "label"
        },
        "language": {
          "type": "string",
          "title": "language"
        },
        "code": {
          "type": "string",
          "title": "code"
        },
        "exclusive": {
          "type": "boolean",
          "title": "exclusive",
          "default": true
        }
      },
      "additionalProperties": false,
      "required": ["label", "language", "code"]
    },
    "PricingPlan": {
      "title": "PricingPlan",
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "title": "name"
        },
        "slug": {
          "type": "string",
          "title": "slug"
        },
        "desc": {
          "type": "string",
          "title": "desc"
        },
        "auth": {
          "type": "boolean",
          "title": "auth"
        },
        "features": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "title": "features"
        },
        "amount": {
          "type": "number",
          "title": "amount",
          "default": 0,
          "minimum": 0
        },
        "requests": {
          "$ref": "#/definitions/PricingPlanMeteredConfig",
          "title": "requests"
        },
        "rateLimit": {
          "oneOf": [{ "$ref": "#/definitions/RateLimit" }, { "type": "null" }],
          "title": "rateLimit"
        }
      },
      "additionalProperties": false,
      "required": ["name"]
    },
    "PricingPlanMeteredConfig": {
      "title": "PricingPlanMeteredConfig",
      "type": "object",
      "properties": {
        "amount": {
          "type": "number",
          "title": "amount",
          "minimum": 0
        },
        "billingScheme": {
          "type": "string",
          "title": "billingScheme",
          "enum": ["per_unit", "tiered"]
        },
        "tiersMode": {
          "type": "string",
          "title": "teirsMode",
          "enum": ["graduated", "volume"]
        },
        "tiers": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/PricingPlanTier"
          },
          "title": "tiers"
        }
      },
      "additionalProperties": false
    },
    "PricingPlanTier": {
      "title": "PricingPlanTier",
      "type": "object",
      "properties": {
        "unitAmount": {
          "type": "number",
          "title": "unitAmount",
          "minimum": 0
        },
        "flatAmount": {
          "type": "number",
          "title": "flatAmount",
          "minimum": 0
        },
        "upTo": {
          "type": "string",
          "title": "upTo"
        }
      },
      "additionalProperties": false,
      "required": ["upTo"]
    },
    "PricingPlanServiceConfig": {
      "title": "PricingPlanServiceConfig",
      "type": "object",
      "properties": {
        "enabled": {
          "type": "boolean",
          "title": "enabled"
        },
        "reportUsage": {
          "type": "boolean",
          "title": "reportUsage"
        },
        "rateLimit": {
          "oneOf": [{ "$ref": "#/definitions/RateLimit" }, { "type": "null" }],
          "title": "rateLimit"
        }
      },
      "additionalProperties": false
    }
  }
}

=== nirjo/SAMS/packages/saasify-cli/fixtures/pricing-plans-billing-scheme-tiered.json
{
  "version": "1.0.0",
  "name": "hello-world",
  "services": [
    {
      "src": "functions/hello-world.ts",
      "immutable": true,
      "reportUsage": false,
      "rateLimit": {
        "requestsInterval": "1d",
        "requestsMaxPerInterval": 1000
      }
    },
    {
      "src": "functions/nala.ts",
      "pricingPlanConfig": {
        "free": {
          "enabled": true,
          "rateLimit": {
            "requestsInterval": 3600,
            "requestsMaxPerInterval": 5
          }
        },
        "unlimited": {
          "reportUsage": false
        }
      }
    }
  ],
  "pricingPlans": [
    {
      "name": "Free",
      "slug": "free",
      "amount": 0,
      "rateLimit": {
        "requestsInterval": "1h",
        "requestsMaxPerInterval": 25
      }
    },
    {
      "name": "Unlimited",
      "slug": "unlimited",
      "amount": 999,
      "requests": {
        "billingScheme": "tiered",
        "tiers": [
          {
            "unitAmount": 0,
            "upTo": "1000"
          },
          {
            "unitAmount": 0.04,
            "upTo": "10000"
          },
          {
            "unitAmount": 0.02,
            "upTo": "inf"
          }
        ]
      }
    }
  ]
}

=== nirjo/SAMS/examples/typescript/check-links/saasify.json
{
  "name": "check-links",
  "description": "Cleanly pull content from any website",
  "alias": "check-links",
  "services": [
    {
      "src": "src/check-links.ts",
      "POST": false,
      "immutable": true,
      "examples": [
        {
          "name": "Basic Usage",
          "input": {
            "urls": [
              "https://www.brown.edu/",
              "https://news.ycombinator.com/",
              "invalid url",
              "https://example.com/not-found-404"
            ]
          }
        }
      ]
    }
  ],
  "saas": {
    "name": "Lively URLs",
    "heading": "Robust URL Liveness",
    "subheading": "Quickly and robustly check large batches of URLs for liveness at scale.",
    "repo": "https://github.com/saasify-sh/saasify/tree/master/examples/typescript/check-links",
    "logo": "media/logo.svg",
    "favicon": "media/favicon.ico",
    "theme": {
      "name": "waves",
      "backgroundImage": "https://images.unsplash.com/photo-1452953008873-ae5837174535?ixlib=rb-1.2.1&auto=format&fit=crop&w=2550&q=80",
      "buttonStyle": "rounded",
      "color": "#4aaef7",
      "wave": false,
      "gradientDark": false,
      "codeBlockDark": true
    }
  }
}

=== nirjo/SAMS/examples/python/wordcloud/saasify.json
{
  "name": "wordcloud",
  "description": "Generate stylish wordclouds from any webpage.",
  "alias": "wordcloud",
  "services": [
    {
      "src": "main.py",
      "immutable": true,
      "examples": [
        {
          "name": "US Constitution",
          "input": {
            "url": "https://www.constituteproject.org/constitution/United_States_of_America_1992",
            "icon": "fas fa-dove",
            "palette": "cartocolors.qualitative.Bold_6"
          }
        },
        {
          "name": "News Article",
          "description": "Create wordcloud from article",
          "input": {
            "url": "https://www.cbc.ca/news/canada/ottawa/snow-storm-remembrance-day-1.5355302",
            "icon": "fab fa-canadian-maple-leaf",
            "palette": "colorbrewer.sequential.Reds_6",
            "gradient": "vertical"
          }
        },
        {
          "name": "YC",
          "description": "Generate from blog post",
          "input": {
            "url": "https://blog.ycombinator.com/ycs-essential-startup-advice/",
            "icon": "fab fa-y-combinator",
            "palette": "cartocolors.qualitative.Pastel_8",
            "gradient": "horizontal"
          }
        }
      ]
    }
  ],
  "pricingPlans": [
    {
      "name": "Free",
      "rateLimit": {
        "requestsInterval": 3600,
        "requestsMaxPerInterval": 15
      }
    },
    {
      "name": "Unlimited",
      "amount": 99,
      "requests": {
        "amount": 0.5
      }
    }
  ],
  "env": {
    "EXTRACT_TOKEN": "@extract_token"
  },
  "saas": {
    "name": "WordCloud",
    "heading": "**Generate Beautiful Wordclouds**",
    "subheading": "An API to create attractive wordcloud previews from any text or webpage.",
    "repo": "https://github.com/saasify-sh/saasify/tree/master/examples/python/wordcloud",
    "logo": "media/logo.svg",
    "favicon": "media/favicon.ico",
    "theme": {
      "name": "waves",
      "backgroundImage": "https://images.unsplash.com/photo-1501630834273-4b5604d2ee31?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2550&q=80",
      "buttonStyle": "standard",
      "color": "#50A9DA",
      "wave": false,
      "gradientDark": false,
      "codeBlockDark": true,
      "codeBlockOutputColor": "white"
    }
  }
}

=== nirjo/SAMS/examples/typescript/sharp/saasify.json
{
  "name": "sharp",
  "alias": "sharp",
  "services": [
    {
      "src": "src/index.ts",
      "immutable": true,
      "examples": [
        {
          "name": "Resize",
          "input": {
            "input": "https://octodex.github.com/images/original.png",
            "ops": [
              {
                "op": "resize",
                "options": {
                  "width": 220
                }
              },
              {
                "op": "webp"
              }
            ]
          }
        }
      ]
    }
  ],
  "saas": {
    "repo": "https://github.com/saasify-sh/saasify/tree/master/examples/typescript/sharp",
    "logo": "./media/logo.svg",
    "favicon": "./media/favicon.ico"
  }
}

=== nirjo/SAMS/packages/saasify-cli/fixtures/pricing-plans-service-overrides.json
{
  "version": "1.0.0",
  "name": "hello-world",
  "services": [
    {
      "src": "functions/hello-world.ts",
      "immutable": true,
      "reportUsage": false,
      "rateLimit": null
    },
    {
      "src": "functions/nala.ts",
      "pricingPlanConfig": {
        "free": {
          "enabled": false
        },
        "unlimited": {
          "reportUsage": false
        }
      }
    }
  ],
  "pricingPlans": [
    {
      "name": "Free",
      "slug": "free",
      "amount": 0,
      "rateLimit": {
        "requestsInterval": "1h",
        "requestsMaxPerInterval": 25
      }
    },
    {
      "name": "Unlimited",
      "slug": "unlimited",
      "amount": 99,
      "rateLimit": null,
      "requests": {
        "amount": 0.04
      }
    }
  ]
}

=== nirjo/SAMS/examples/typescript/color/saasify.json
{
  "name": "color",
  "description": "Color conversion and manipulation API. ðŸŒˆ",
  "alias": "color",
  "services": [
    {
      "src": "index.ts",
      "immutable": true,
      "examples": [
        {
          "name": "Convert to HSV",
          "input": {
            "input": "#f08a5d",
            "outputType": "hsv"
          }
        },
        {
          "name": "Convert to HSV",
          "input": {
            "input": "#f08a5d",
            "outputType": "hsv"
          }
        }
      ]
    }
  ],
  "saas": {
    "heading": "**Color** Conversion and Manipulation",
    "subheading": "Simple API handling the most common color conversion and manipulation functions.",
    "repo": "https://github.com/saasify-sh/saasify/tree/master/examples/typescript/color",
    "logo": "./media/logo.svg",
    "favicon": "./media/favicon.ico",
    "theme": {
      "name": "waves",
      "backgroundImage": "https://images.unsplash.com/photo-1464820453369-31d2c0b651af?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1700&q=80",
      "buttonStyle": "rounded",
      "color": "#ff6e6c",
      "wave": false,
      "gradientDark": false,
      "codeBlockDark": true
    }
  }
}

=== nirjo/SAMS/examples/typescript/article-extraction/saasify.json
{
  "name": "article-extraction",
  "description": "Cleanly pull content from any website",
  "alias": "article-extraction",
  "services": [
    {
      "src": "src/extract-article.ts",
      "POST": false,
      "examples": [
        {
          "name": "Extract Wikipedia Article",
          "input": {
            "url": "https://en.wikipedia.org/wiki/Joker_(2019_film)"
          }
        }
      ]
    }
  ],
  "saas": {
    "name": "Article Extraction",
    "heading": "Clean article extraction",
    "subheading": "High quality article extraction at scale.",
    "repo": "https://github.com/saasify-sh/saasify/tree/master/examples/typescript/article-extraction",
    "logo": "media/logo.svg",
    "favicon": "media/favicon.ico",
    "theme": {
      "name": "waves",
      "backgroundImage": "https://images.unsplash.com/photo-1557428894-56bcc97113fe?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1352&q=80",
      "buttonStyle": "rounded",
      "color": "#4aaef7",
      "wave": false,
      "gradientDark": false,
      "codeBlockDark": true
    }
  }
}

=== nirjo/SAMS/packages/saasify-cli/fixtures/pricing-plans-simple.json
{
  "version": "1.0.0",
  "name": "hello-world",
  "services": [
    {
      "src": "functions/hello-world.ts"
    }
  ],
  "pricingPlans": [
    {
      "name": "Free",
      "slug": "free",
      "amount": 0,
      "rateLimit": {
        "requestsInterval": "1h",
        "requestsMaxPerInterval": 25
      }
    },
    {
      "name": "Unlimited",
      "slug": "unlimited",
      "amount": 99,
      "rateLimit": null
    }
  ]
}
