=== nirjo/SAMS/packages/saasify-cli/lib/schemas/config.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/Config",
  "definitions": {
    "Config": {
      "title": "Config",
      "type": "object",
      "properties": {
        "saasifyVersion": {
          "title": "saasifyVersion",
          "default": 1,
          "oneOf": [{ "type": "number" }, { "type": "string" }]
        },
        "version": {
          "title": "version",
          "default": "0.1.0",
          "oneOf": [{ "type": "number" }, { "type": "string" }]
        },
        "name": {
          "type": "string",
          "title": "name"
        },
        "description": {
          "type": "string",
          "title": "description"
        },
        "alias": {
          "type": "string",
          "title": "alias"
        },
        "build": {
          "type": "object",
          "title": "build",
          "additionalProperties": true
        },
        "env": {
          "type": "object",
          "title": "env",
          "additionalProperties": true
        },
        "saas": {
          "type": "object",
          "title": "saas",
          "additionalProperties": true
        },
        "openapi": {
          "title": "openapi",
          "oneOf": [
            { "type": "object", "additionalProperties": true },
            { "type": "string" }
          ]
        },
        "services": {
          "type": "array",
          "title": "services",
          "items": {
            "$ref": "#/definitions/Service"
          }
        },
        "coupons": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Coupon"
          },
          "title": "coupons"
        },
        "headers": {
          "type": "object",
          "title": "headers",
          "additionalProperties": true
        },
        "immutable": {
          "type": "boolean",
          "title": "immutable"
        },
        "pricingPlans": {
          "type": "array",
          "minItems": 2,
          "maxItems": 5,
          "items": {
            "$ref": "#/definitions/PricingPlan"
          },
          "title": "pricingPlans"
        }
      },
      "additionalProperties": false
    },
    "Example": {
      "title": "Example",
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "title": "name"
        },
        "description": {
          "type": "string",
          "title": "description"
        },
        "input": {
          "type": "object",
          "title": "input"
        },
        "inputContentType": {
          "type": "string",
          "title": "inputContentType"
        },
        "snippet": {
          "$ref": "#/definitions/Snippet",
          "title": "snippet"
        },
        "additionalProperties": false
      },
      "required": ["name", "input"]
    },
    "Coupon": {
      "title": "Coupon",
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "title": "name"
        },
        "currency": {
          "type": "string",
          "title": "currency"
        },
        "amount_off": {
          "type": "number",
          "title": "amount_off"
        },
        "percent_off": {
          "type": "number",
          "title": "percent_off"
        },
        "duration": {
          "type": "string",
          "title": "duration"
        },
        "duration_in_months": {
          "type": "number",
          "title": "duration_in_months"
        },
        "redeem_by": {
          "type": "string",
          "title": "redeem_by"
        },
        "max_redemptions": {
          "type": "number",
          "title": "max_redemptions"
        },
        "additionalProperties": false
      },
      "required": ["duration"]
    },
    "Service": {
      "title": "Service",
      "type": "object",
      "properties": {
        "src": {
          "type": "string",
          "title": "src"
        },
        "name": {
          "type": "string",
          "title": "name"
        },
        "path": {
          "type": "string",
          "title": "path"
        },
        "timeout": {
          "type": "number",
          "title": "timeout"
        },
        "examples": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Example"
          },
          "title": "examples"
        },
        "config": {
          "type": "object",
          "title": "config",
          "additionalProperties": true
        },
        "GET": {
          "type": "boolean",
          "title": "GET"
        },
        "POST": {
          "type": "boolean",
          "title": "POST"
        },
        "headers": {
          "type": "object",
          "title": "headers",
          "additionalProperties": true
        },
        "immutable": {
          "type": "boolean",
          "title": "immutable"
        },
        "reportUsage": {
          "type": "boolean",
          "title": "reportUsage"
        },
        "rateLimit": {
          "oneOf": [{ "$ref": "#/definitions/RateLimit" }, { "type": "null" }],
          "title": "rateLimit"
        },
        "pricingPlanConfig": {
          "type": "object",
          "title": "pricingPlanConfig",
          "patternProperties": {
            "^.*$": { "$ref": "#/definitions/PricingPlanServiceConfig" }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    },
    "RateLimit": {
      "title": "RateLimit",
      "type": "object",
      "properties": {
        "requests": {
          "type": "boolean",
          "title": "enabled",
          "default": true
        },
        "requestsInterval": {
          "title": "requestsInterval",
          "default": "1h",
          "oneOf": [{ "type": "number" }, { "type": "string" }]
        },
        "requestsMaxPerInterval": {
          "type": "number",
          "title": "requestsMaxPerInterval",
          "default": 1000
        }
      },
      "additionalProperties": false
    },
    "Snippet": {
      "title": "Snippet",
      "type": "object",
      "properties": {
        "label": {
          "type": "string",
          "title": "label"
        },
        "language": {
          "type": "string",
          "title": "language"
        },
        "code": {
          "type": "string",
          "title": "code"
        },
        "exclusive": {
          "type": "boolean",
          "title": "exclusive",
          "default": true
        }
      },
      "additionalProperties": false,
      "required": ["label", "language", "code"]
    },
    "PricingPlan": {
      "title": "PricingPlan",
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "title": "name"
        },
        "slug": {
          "type": "string",
          "title": "slug"
        },
        "desc": {
          "type": "string",
          "title": "desc"
        },
        "auth": {
          "type": "boolean",
          "title": "auth"
        },
        "features": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "title": "features"
        },
        "amount": {
          "type": "number",
          "title": "amount",
          "default": 0,
          "minimum": 0
        },
        "requests": {
          "$ref": "#/definitions/PricingPlanMeteredConfig",
          "title": "requests"
        },
        "rateLimit": {
          "oneOf": [{ "$ref": "#/definitions/RateLimit" }, { "type": "null" }],
          "title": "rateLimit"
        }
      },
      "additionalProperties": false,
      "required": ["name"]
    },
    "PricingPlanMeteredConfig": {
      "title": "PricingPlanMeteredConfig",
      "type": "object",
      "properties": {
        "amount": {
          "type": "number",
          "title": "amount",
          "minimum": 0
        },
        "billingScheme": {
          "type": "string",
          "title": "billingScheme",
          "enum": ["per_unit", "tiered"]
        },
        "tiersMode": {
          "type": "string",
          "title": "teirsMode",
          "enum": ["graduated", "volume"]
        },
        "tiers": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/PricingPlanTier"
          },
          "title": "tiers"
        }
      },
      "additionalProperties": false
    },
    "PricingPlanTier": {
      "title": "PricingPlanTier",
      "type": "object",
      "properties": {
        "unitAmount": {
          "type": "number",
          "title": "unitAmount",
          "minimum": 0
        },
        "flatAmount": {
          "type": "number",
          "title": "flatAmount",
          "minimum": 0
        },
        "upTo": {
          "type": "string",
          "title": "upTo"
        }
      },
      "additionalProperties": false,
      "required": ["upTo"]
    },
    "PricingPlanServiceConfig": {
      "title": "PricingPlanServiceConfig",
      "type": "object",
      "properties": {
        "enabled": {
          "type": "boolean",
          "title": "enabled"
        },
        "reportUsage": {
          "type": "boolean",
          "title": "reportUsage"
        },
        "rateLimit": {
          "oneOf": [{ "$ref": "#/definitions/RateLimit" }, { "type": "null" }],
          "title": "rateLimit"
        }
      },
      "additionalProperties": false
    }
  }
}

=== nirjo/SAMS/examples/typescript/lqip/saasify.json
{
  "name": "lqip",
  "description": "An API for generating Low Quality Image Placeholders (LQIP).",
  "alias": "lqip",
  "immutable": true,
  "services": [
    {
      "src": "src/url-to-base64.ts",
      "POST": false,
      "examples": [
        {
          "name": "Basic Usage",
          "input": {
            "url": "https://octodex.github.com/images/twenty-percent-cooler-octocat.png"
          }
        }
      ]
    },
    {
      "src": "src/url-to-image.ts",
      "POST": false,
      "examples": [
        {
          "name": "Basic Usage",
          "input": {
            "url": "https://octodex.github.com/images/surftocat.png"
          }
        }
      ]
    },
    {
      "src": "src/image-to-base64.ts",
      "GET": false
    },
    {
      "src": "src/image-to-image.ts",
      "GET": false
    }
  ],
  "saas": {
    "name": "LQIP",
    "heading": "Low Quality Image Placeholders",
    "subheading": "An API for generating Low Quality Image Placeholders (LQIP).",
    "repo": "https://github.com/saasify-sh/saasify/tree/master/examples/typescript/lqip",
    "logo": "media/logo.svg",
    "favicon": "media/favicon.ico",
    "theme": {
      "name": "waves",
      "backgroundImage": "https://images.unsplash.com/photo-1499346146792-b008e446261f?ixlib=rb-1.2.1&auto=format&fit=crop&w=2550&q=80",
      "buttonStyle": "rounded",
      "color": "#0a8cfb",
      "wave": false,
      "gradientDark": false,
      "codeBlockDark": true
    }
  }
}

=== nirjo/SAMS/examples/typescript/remove-bg/saasify.json
{
  "name": "remove-bg",
  "description": "Smart image background removal",
  "services": [
    {
      "src": "src/url.ts",
      "immutable": true,
      "examples": [
        {
          "name": "Person",
          "input": {
            "url": "https://raw.githubusercontent.com/saasify-sh/saasify/master/examples/typescript/remove-bg/examples/cc.jpg"
          }
        },
        {
          "name": "Product",
          "input": {
            "url": "https://raw.githubusercontent.com/saasify-sh/saasify/master/examples/typescript/remove-bg/examples/pg.jpg"
          }
        },
        {
          "name": "Car",
          "input": {
            "url": "https://raw.githubusercontent.com/saasify-sh/saasify/master/examples/typescript/remove-bg/examples/jb.jpg"
          }
        }
      ]
    }
  ],
  "pricingPlans": [
    {
      "name": "Free",
      "rateLimit": {
        "requestsInterval": 86400,
        "requestsMaxPerInterval": 5
      }
    },
    {
      "name": "Unlimited",
      "amount": 999,
      "requests": {
        "amount": 50
      }
    }
  ],
  "env": {
    "REMOVE_BG_API_KEY": "@remove-bg-api-key"
  },
  "saas": {
    "name": "Remove BG",
    "repo": "https://github.com/saasify-sh/saasify/tree/master/examples/typescript/remove-bg",
    "logo": "media/logo.svg",
    "favicon": "media/favicon.ico",
    "sections": {
      "hero": {
        "image": "https://raw.githubusercontent.com/saasify-sh/saasify/master/examples/typescript/remove-bg/media/splash-0.jpg"
      }
    }
  }
}

=== nirjo/SAMS/examples/typescript/natural/saasify.json
{
  "name": "natural",
  "description": "NLP toolkit",
  "alias": "natural",
  "immutable": true,
  "services": [
    {
      "src": "./src/approx-string-search.ts"
    },
    {
      "src": "./src/distance.ts",
      "config": {
        "includeFiles": ["./node_modules/natural/**/*"]
      }
    },
    {
      "src": "./src/singularize.ts",
      "config": {
        "includeFiles": ["./node_modules/natural/**/*"]
      }
    },
    {
      "src": "./src/pluralize.ts",
      "config": {
        "includeFiles": ["./node_modules/natural/**/*"]
      }
    },
    {
      "src": "./src/nth.ts",
      "config": {
        "includeFiles": ["./node_modules/natural/**/*"]
      }
    },
    {
      "src": "./src/phonetics.ts",
      "config": {
        "includeFiles": ["./node_modules/natural/**/*"]
      }
    },
    {
      "src": "./src/sentiment.ts",
      "config": {
        "includeFiles": [
          "./node_modules/afinn-165/**/*",
          "./node_modules/natural/**/*"
        ]
      }
    },
    {
      "src": "./src/stem.ts",
      "config": {
        "includeFiles": ["./node_modules/natural/**/*"]
      }
    },
    {
      "src": "./src/tokenize.ts",
      "config": {
        "includeFiles": ["./node_modules/natural/**/*"]
      }
    },
    {
      "src": "./src/n-grams.ts",
      "config": {
        "includeFiles": ["./node_modules/natural/**/*"]
      }
    },
    {
      "src": "./src/n-grams-zh.ts",
      "config": {
        "includeFiles": ["./node_modules/natural/**/*"]
      }
    },
    {
      "src": "./src/lookup.ts",
      "config": {
        "includeFiles": [
          "./node_modules/natural/**/*",
          "./node_modules/wordnet-db/**/*"
        ]
      }
    }
  ],
  "saas": {
    "repo": "https://github.com/saasify-sh/saasify/tree/master/examples/typescript/natural",
    "heading": "**NLP** APIs",
    "subheading": "Powered by the most popular Node.js NLP toolkit.",
    "logo": "media/logo.svg",
    "favicon": "media/favicon.ico",
    "theme": {
      "name": "waves",
      "backgroundImage": "https://images.unsplash.com/photo-1456081101716-74e616ab23d8?ixlib=rb-1.2.1&auto=format&fit=crop&w=2555&q=80",
      "buttonStyle": "rounded",
      "color": "#f38181",
      "wave": false,
      "gradientDark": false,
      "codeBlockDark": true
    }
  }
}

=== nirjo/SAMS/examples/typescript/imagemin/saasify.json
{
  "name": "imagemin",
  "description": "Image optimization as a service",
  "alias": "imagemin",
  "immutable": true,
  "services": [
    {
      "src": "src/url.ts",
      "examples": [
        {
          "name": "JPEG",
          "description": "Optimize image by URL",
          "input": {
            "url": "https://source.unsplash.com/V6TWE6h8gyg/1600x900"
          }
        },
        {
          "name": "PNG",
          "description": "Optimize image by URL",
          "input": {
            "url": "https://octodex.github.com/images/original.png"
          }
        }
      ]
    },
    {
      "src": "src/index.ts"
    }
  ],
  "saas": {
    "repo": "https://github.com/saasify-sh/saasify/tree/master/examples/typescript/imagemin",
    "name": "imagemin",
    "heading": "**Reduce image sizes by up to 60%**",
    "subheading": "Lightning-fast API to serve optimized versions of any image asset, in any environment.",
    "logo": "media/logo.svg",
    "favicon": "media/favicon.ico",
    "theme": {
      "name": "waves",
      "backgroundImage": "https://images.unsplash.com/photo-1565638459249-c85cbb2faaa8?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80",
      "buttonStyle": "rounded",
      "color": "#2f8aad",
      "wave": false,
      "gradientDark": true,
      "codeBlockDark": true,
      "codeBlockOutputFlush": true
    },
    "features": [
      {
        "name": "Minify any image",
        "desc": "Reduce image sizes for PNGs, JPEGs, GIFs and more by up to 60%.",
        "icon": "media/icons/images.svg"
      },
      {
        "name": "Lightning-fast",
        "desc": "Industry leading image processing times mean you'll never wait long.",
        "icon": "media/icons/fast.svg"
      },
      {
        "name": "Reduce costs",
        "desc": "Image processing at scale is expensive. We'll handle that; you focus on your business.",
        "icon": "media/icons/savings.svg"
      },
      {
        "name": "Free to try",
        "desc": "100 images / mo for free, then only pay for what you use. See [our pricing](/pricing).",
        "icon": "media/icons/happy.svg"
      },
      {
        "name": "Plugin ecosystem",
        "desc": "Leverage an ecosystem with [dozens of plugins](https://www.npmjs.com/search?q=keywords:imageminplugin), from pngquant to gifsicle.",
        "icon": "media/icons/plugins.svg"
      },
      {
        "name": "Support open source",
        "desc": "Profits support the authors of [imagemin](https://www.github.com/imagemin/imagemin), the popular Node.js lib with 3,000,000+ monthly downloads!",
        "icon": "media/icons/opensource.svg"
      }
    ]
  },
  "pricingPlans": [
    {
      "name": "Free",
      "rateLimit": {
        "requestsInterval": 2628000,
        "requestsMaxPerInterval": 100
      }
    },
    {
      "name": "Unlimited",
      "amount": 99,
      "requests": {
        "amount": 0.24
      }
    }
  ]
}

=== nirjo/SAMS/examples/typescript/text-to-ascii-art/saasify.json
{
  "name": "text-to-ascii-art",
  "description": "Converts text to ascii art.",
  "alias": "text-to-ascii-art",
  "services": [
    {
      "src": "index.ts",
      "immutable": true,
      "examples": [
        {
          "name": "Ghost",
          "input": {
            "text": "Boo!",
            "font": "Ghost"
          }
        },
        {
          "name": "Big Money-ne",
          "input": {
            "text": "Saasify",
            "font": "Big Money-ne"
          }
        },
        {
          "name": "ANSI Shadow",
          "input": {
            "text": "Saasify",
            "font": "ANSI Shadow"
          }
        },
        {
          "name": "Bloody",
          "input": {
            "text": "Saasify",
            "font": "Bloody"
          }
        },
        {
          "name": "Alligator",
          "input": {
            "text": "Saasify",
            "font": "Alligator"
          }
        },
        {
          "name": "Alligator2",
          "input": {
            "text": "Saasify",
            "font": "Alligator2"
          }
        },
        {
          "name": "Banner3-D",
          "input": {
            "text": "Saasify",
            "font": "Banner3-D"
          }
        },
        {
          "name": "Georgia11",
          "input": {
            "text": "Saasify",
            "font": "Georgia11"
          }
        },
        {
          "name": "Roman",
          "input": {
            "text": "Saasify",
            "font": "Roman"
          }
        },
        {
          "name": "Poison",
          "input": {
            "text": "Saasify",
            "font": "Poison"
          }
        },
        {
          "name": "Small Poison",
          "input": {
            "text": "Saasify",
            "font": "Small Poison"
          }
        },
        {
          "name": "Doh",
          "input": {
            "text": "Saasify",
            "font": "Doh"
          }
        }
      ]
    }
  ],
  "saas": {
    "heading": "Text to **ASCII ART**",
    "subheading": "Simple API for converting text to hundreds of styles of ASCII art.",
    "repo": "https://github.com/saasify-sh/saasify/tree/master/examples/typescript/text-to-ascii-art",
    "logo": "./media/logo.svg",
    "favicon": "./media/favicon.ico",
    "theme": {
      "name": "waves",
      "backgroundImage": "https://images.unsplash.com/photo-1558777097-28d89959d145?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2167&q=80",
      "buttonStyle": "rounded",
      "color": "#3f72af",
      "wave": false,
      "gradientDark": false,
      "codeBlockDark": true
    }
  }
}

=== nirjo/SAMS/examples/typescript/meta-stock/saasify.json
{
  "name": "meta-stock",
  "description": "TODO",
  "alias": "meta-stock",
  "services": [
    {
      "src": "src/search-images.ts",
      "immutable": true,
      "examples": [
        {
          "name": "Search for images of cats",
          "input": {
            "query": "cats"
          }
        }
      ]
    }
  ],
  "env": {
    "UNSPLASH_ACCESS_KEY": "@unsplash_access_key",
    "UNSPLASH_SECRET_KEY": "@unsplash_secret_key",
    "PIXABAY_API_KEY": "@pixabay_api_key"
  },
  "saas": {
    "name": "MetaStock",
    "heading": "Royalty free stock media search",
    "subheading": "Meta search engine for the best royalty free stock images, gifs, and videos.",
    "repo": "https://github.com/saasify-sh/saasify/tree/master/examples/typescript/meta-stock",
    "logo": "media/logo.svg",
    "favicon": "media/favicon.png",
    "theme": {
      "name": "waves",
      "backgroundImage": "https://images.unsplash.com/photo-1549916571-9b2c630403dc?ixlib=rb-1.2.1&auto=format&fit=crop&w=2550&q=80",
      "buttonStyle": "rounded",
      "color": "#4aaef7",
      "wave": false,
      "gradientDark": false,
      "codeBlockDark": true
    }
  }
}
